questions = ["What is the capital of France?", "What is the capital of Germany?","What is the capital of Italy?",
             "What is the capital of Spain?", "What is the capital of Portugal?","What is the capital of Switzerland?",
             "What is the capital of Austria?","Which planet shares its name with a dog?", "Who wrote: To Kill a Mockingbird?",
             "Who wrote Flowers in the Attic?", "How many floors does the Eiffel Tower have? (Write the number)", "Which country produces the most tea?",
             "Which country gives students the longest summer holiday?", "How many pounds are in a ton?", 
             "How many wonders of the world exists?", "Is Dubai a country or city?", "How many planets make up the solar system?",
             "What is the largest bone in the human body?", "Which singer real name is Robyn Fenty?",
             "Which singer is the Queen of Christmas?", "What is the world most favorite type of fries?",
             "Which continent does the country Mongolia belong?", "What is the largest continent?",
             "The world most famous chicken and fries food joint?", "Which continent is the country Morocco located in?",
             "Which country has the national dress as the sari and is known for wearing lots of gold jewellery?",
             "Which singer had their song featured in the film Titanic?", "Which continent is the coldest?", 
             "Who is noted as the fastest man in the world?", "What is the longest river in the world?", "Which country has the most pyramids?",
             "Which movie series has the most number of movies made?", "Where is the pyramid of Giza?", "What is the name of the Disney princess who slept the most?",
             "Which Disney princess was the maid of her family?", "Which Disney Princess had skin as white as snow?",
             "Who sang: I will always love you?", "Who sang: A moment like this?", "Which South American country speaks Portugese?",
             "What do you called ice-cream in a bowl?", "Which fruit has the word apple in it but is not an actual type of apple?",
             "Which fruit has the same name as its colour?", "Which Disney movie main character did not want to grow up/feared growing up?",
             "Which movie character nose grows longer as he lies?", "Which princess has the longest hair?",
             "Which superheroe real name is Clark Kent?", "Which superheroe is: a wonder?", "What is the typical name for a juice with a blend/mixture of flavours?",
             "Which movie series is about a young wizard boy?", "What is the highest mountain peak?", "What colour is a giraffe's tongue?",
             "What are baby rabbits called?", "How many players make up a football team? (Write the number)", 
             "Which food is pickles made from?", "What is the unit of energy called?", "Which bear loves the cold?", "Which flake is seen in winter?"]

answers = ["Paris", "Berlin", "Rome", "Madrid", "Lisbon", "Bern" ,"Vienna", "Pluto", "Harper Lee", "V.C. Andrews","3",
           "China","Italy", "2,000", "7", "City", "8", "Femur", "Rihanna", "Mariah Carey", "French fries",
           "Asia", "Asia", "KFC", "Africa", "India", "Celine Dion", "Antarctica","Usain Bolt", "Nile", "Sudan", "Fast and the Furious",
           "Egypt", "Aurora", "Cinderella", "Snow White", "Whitney Houston", "Kelly Clarkson", "Brazil", "Sundae", "Pineapple",
           "Orange", "Peter Pan", "Pinnochio", "Rapunzel", "Superman", "Wonder Woman", "Fruit punch", "Harry Potter",
           "Mount Everest", "Purple", "Kits", "11", "Cucumber", "Joule", "Polar Bear", "Snowflake"]